server:
  port: 8888

spring:
  application:
    name: ywy-ltxxzsxt-provide
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  #she zhi shang chuan wenjian daxiao

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ltxxzsxt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  mybatis-plus:
    # saomiao mapper.xml
    mapper-locations: classpath:/mapper/*Mapper.xml
    configuration:
      jdbc-type-for-null: 'null'
